services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 #optional, only if you want to access the db directly from your host.

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HTTP_PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json #optional, for realm imports.

volumes:
  db-data:
